from __future__ import annotations

import copy
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import yaml
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field


APP_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = APP_ROOT.parent
FRAMEWORK_ROOT = REPO_ROOT / "framework"
DEFAULT_WORKSPACE = REPO_ROOT / "examples"
UI_ROOT = APP_ROOT / "ui"
LOGO_PATH = REPO_ROOT / "draftlogo.png"

CATALOG_FOLDERS = (
    "abbs",
    "rbbs",
    "reference-architectures",
    "sdms",
    "product-services",
    "saas-services",
    "ards",
    "sessions",
    "objects",
)
CONFIGURATION_FOLDERS = (
    "odcs",
    "odc-overrides",
    "object-patches",
    "compliance-frameworks",
    "compliance-profiles",
    "object-types",
    "automation-targets",
    "domains",
)
OBJECT_TYPE_FOLDERS = {
    "abb": ("catalog", "abbs"),
    "ard": ("catalog", "ards"),
    "drafting_session": ("catalog", "sessions"),
    "rbb": ("catalog", "rbbs"),
    "reference_architecture": ("catalog", "reference-architectures"),
    "software_distribution_manifest": ("catalog", "sdms"),
    "compliance_framework": ("configurations", "compliance-frameworks"),
    "compliance_profile": ("configurations", "compliance-profiles"),
    "domain": ("configurations", "domains"),
    "object_patch": ("configurations", "object-patches"),
    "odc": ("configurations", "odc-overrides"),
}
ALLOWED_DRAFTSMAN_MODES = {"external", "embedded", "disabled"}
ALLOWED_EMBEDDED_PROVIDERS = {"openai"}
ALLOWED_EMBEDDED_AUTH_TYPES = {"oauth"}
DISALLOWED_SECRET_KEYS = {
    "apiKey",
    "api_key",
    "apiKeyRef",
    "api_key_ref",
    "openaiApiKey",
    "openai_api_key",
}


class WorkspaceRequest(BaseModel):
    workspace: Optional[str] = Field(default=None, description="Workspace root path.")


class WorkspaceInitRequest(BaseModel):
    workspace: str
    name: Optional[str] = None
    repository: Optional[dict[str, Any]] = None
    framework: Optional[dict[str, Any]] = None


class WorkspaceSettingsRequest(WorkspaceRequest):
    config: dict[str, Any]


class ObjectWriteRequest(WorkspaceRequest):
    document: dict[str, Any]
    layer: str = "auto"
    path: Optional[str] = None
    validateAfter: bool = True


class ObjectPatchWriteRequest(WorkspaceRequest):
    target: str
    patch: dict[str, Any]
    purpose: str = "override"
    name: Optional[str] = None
    description: Optional[str] = None
    owner: Optional[dict[str, Any]] = None
    tags: Optional[list[str]] = None
    catalogStatus: str = "draft"
    lifecycleStatus: str = "invest"
    validateAfter: bool = True


class CommitRequest(WorkspaceRequest):
    message: str
    paths: Optional[list[str]] = None


class PushRequest(WorkspaceRequest):
    remote: str = "origin"
    branch: Optional[str] = None


class PublishRequest(WorkspaceRequest):
    base: str = "main"
    head: str = "dev"
    title: str = "Publish DRAFT catalog updates"
    body: str = "Generated by the DRAFT App."
    mode: str = "pull-request"


class DraftsmanChatRequest(WorkspaceRequest):
    message: str
    contextObjectId: Optional[str] = None


app = FastAPI(
    title="DRAFT App API",
    version="0.1.0",
    description="API-first surface for DRAFT workspaces, UI clients, and AI agents.",
)

if UI_ROOT.exists():
    app.mount("/ui", StaticFiles(directory=UI_ROOT), name="ui")


def run(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            cwd=str(cwd),
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise HTTPException(status_code=500, detail=f"Command not available: {command[0]}") from exc


def resolve_workspace(workspace: Optional[str] = None, must_exist: bool = True) -> Path:
    raw = workspace or os.environ.get("DRAFT_WORKSPACE") or str(DEFAULT_WORKSPACE)
    root = Path(raw).expanduser().resolve()
    if must_exist and not root.exists():
        raise HTTPException(status_code=404, detail=f"Workspace does not exist: {root}")
    return root


def workspace_config_path(workspace: Path) -> Path:
    return workspace / ".draft" / "workspace.yaml"


def read_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    return data if isinstance(data, dict) else {}


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(data, handle, sort_keys=False, allow_unicode=False)


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9.-]+", "-", value.lower()).strip(".-") or "object"


def safe_workspace_path(workspace: Path, relative_path: str) -> Path:
    candidate = (workspace / relative_path).resolve()
    if not candidate.is_relative_to(workspace.resolve()):
        raise HTTPException(status_code=400, detail="Path must stay inside the workspace")
    return candidate


def yaml_files(root: Path, folders: tuple[str, ...]) -> list[Path]:
    files: list[Path] = []
    for folder in folders:
        candidate = root / folder
        if candidate.exists():
            files.extend(sorted(candidate.rglob("*.yaml")))
    return files


def object_row(path: Path, root: Path) -> dict[str, Any]:
    data = read_yaml(path)
    row = dict(data)
    row.setdefault("id", path.stem)
    row.setdefault("name", path.stem)
    row.setdefault("type", "yaml")
    row["source"] = path.relative_to(root).as_posix() if path.is_relative_to(root) else path.as_posix()
    return row


def deep_merge(base: Any, patch: Any) -> Any:
    if isinstance(base, dict) and isinstance(patch, dict):
        merged = copy.deepcopy(base)
        for key, value in patch.items():
            if key in {"id", "type"}:
                continue
            merged[key] = deep_merge(merged.get(key), value)
        return merged
    return copy.deepcopy(patch)


def apply_object_patches(objects: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    patched = dict(objects)
    for obj in objects.values():
        if obj.get("type") != "object_patch":
            continue
        target_id = str(obj.get("target", ""))
        patch = obj.get("patch")
        if target_id and target_id in patched and isinstance(patch, dict):
            patched[target_id] = deep_merge(patched[target_id], patch)
    return patched


def validate_workspace_result(workspace: Path) -> dict[str, Any]:
    completed = run(["python3", str(FRAMEWORK_ROOT / "tools" / "validate.py"), "--workspace", str(workspace)], REPO_ROOT)
    return {
        "ok": completed.returncode == 0,
        "returnCode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def framework_pin() -> dict[str, str]:
    commit = run(["git", "rev-parse", "HEAD"], REPO_ROOT)
    return {
        "source": "https://github.com/dsackr/draft-framework.git",
        "pinnedRef": "main",
        "pinnedCommit": commit.stdout.strip() if commit.returncode == 0 else "",
    }


def draftsman_default_config() -> dict[str, Any]:
    return {
        "mode": "external",
        "external": {
            "enabled": True,
            "description": "Use an external AI agent with AGENTS.md, AI_INDEX.md, and the DRAFT App API.",
            "entrypoints": [
                "AGENTS.md",
                "AI_INDEX.md",
                "framework/docs/draftsman.md",
                "app/api",
            ],
        },
        "embedded": {
            "enabled": False,
            "provider": "openai",
            "model": "",
            "auth": {
                "type": "oauth",
                "clientIdRef": "DRAFT_OPENAI_OAUTH_CLIENT_ID",
                "clientSecretRef": "DRAFT_OPENAI_OAUTH_CLIENT_SECRET",
                "redirectUri": "http://127.0.0.1:8000/api/draftsman/oauth/openai/callback",
                "tokenStorage": "runtime",
                "apiKeysAllowed": False,
            },
        },
        "security": {
            "storeSecretsInWorkspace": False,
            "sendGitCredentialsToModel": False,
            "writeRequiresAppValidation": True,
        },
    }


def find_disallowed_secret_keys(node: Any, path: str = "draftsman") -> list[str]:
    matches: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            next_path = f"{path}.{key}"
            if key in DISALLOWED_SECRET_KEYS:
                matches.append(next_path)
            matches.extend(find_disallowed_secret_keys(value, next_path))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            matches.extend(find_disallowed_secret_keys(value, f"{path}[{index}]"))
    return matches


def draftsman_config_status(config: dict[str, Any]) -> dict[str, Any]:
    draftsman = config.get("draftsman")
    if not isinstance(draftsman, dict):
        draftsman = draftsman_default_config()

    issues: list[str] = []
    mode = draftsman.get("mode", "external")
    if mode not in ALLOWED_DRAFTSMAN_MODES:
        issues.append(f"draftsman.mode must be one of {sorted(ALLOWED_DRAFTSMAN_MODES)}")

    embedded = draftsman.get("embedded", {})
    if not isinstance(embedded, dict):
        embedded = {}
    provider = embedded.get("provider", "openai")
    if provider not in ALLOWED_EMBEDDED_PROVIDERS:
        issues.append("Only OpenAI is allowed as an embedded Draftsman provider in this version")

    auth = embedded.get("auth", {})
    if not isinstance(auth, dict):
        auth = {}
    auth_type = auth.get("type", "oauth")
    if auth_type not in ALLOWED_EMBEDDED_AUTH_TYPES:
        issues.append("Only OAuth is allowed for embedded Draftsman auth; API keys are not allowed")
    if auth.get("apiKeysAllowed") is not False:
        issues.append("draftsman.embedded.auth.apiKeysAllowed must remain false")
    if auth.get("tokenStorage") in {"workspace", "file", "files"}:
        issues.append("OAuth tokens must not be stored in workspace files")

    secret_keys = find_disallowed_secret_keys(draftsman)
    if secret_keys:
        issues.append(f"Workspace config must not contain API key fields: {', '.join(secret_keys)}")

    oauth_env_ready = bool(
        os.environ.get(str(auth.get("clientIdRef", "")))
        and os.environ.get(str(auth.get("clientSecretRef", "")))
    )
    return {
        "ok": not issues,
        "mode": mode,
        "embeddedProvider": provider,
        "embeddedAuth": auth_type,
        "externalAgentAvailable": mode in {"external", "embedded"},
        "embeddedDraftsmanAvailable": False,
        "embeddedImplementationStatus": "configuration-only",
        "oauthRuntimeConfigured": oauth_env_ready,
        "issues": issues,
        "note": "External AI agents can use the repo and app API now. Embedded Draftsman model calls are not implemented until OAuth-based OpenAI access is confirmed for this use case.",
    }


def workspace_defaults(root: Path, request: WorkspaceInitRequest) -> tuple[dict[str, Any], dict[str, Any]]:
    framework = framework_pin()
    framework.update(request.framework or {})
    config = {
        "schemaVersion": "1.0",
        "workspace": {
            "name": request.name or root.name,
            "mode": "shared-app",
        },
        "repository": {
            "provider": "github",
            "owner": "",
            "name": root.name,
            "defaultBranch": "main",
            "devBranch": "dev",
            "publishMode": "pull-request",
        },
        "framework": framework,
        "paths": {
            "catalog": "catalog",
            "configurations": "configurations",
        },
        "auth": {
            "localMode": "gh",
            "sharedAppMode": "github-app",
        },
        "draftsman": draftsman_default_config(),
    }
    if request.repository:
        config["repository"].update(request.repository)
    lock = {
        "schemaVersion": "1.0",
        "framework": {
            **framework,
            "updatedAt": now_iso(),
        },
    }
    return config, lock


def initialize_workspace_files(root: Path, request: WorkspaceInitRequest) -> dict[str, Any]:
    root.mkdir(parents=True, exist_ok=True)
    for folder in CATALOG_FOLDERS:
        (root / "catalog" / folder).mkdir(parents=True, exist_ok=True)
    for folder in CONFIGURATION_FOLDERS:
        (root / "configurations" / folder).mkdir(parents=True, exist_ok=True)
    (root / ".draft").mkdir(parents=True, exist_ok=True)

    config, lock = workspace_defaults(root, request)
    config_path = root / ".draft" / "workspace.yaml"
    lock_path = root / ".draft" / "framework.lock"
    if not config_path.exists():
        write_yaml(config_path, config)
    if not lock_path.exists():
        write_yaml(lock_path, lock)
    return {
        "workspace": str(root),
        "created": True,
        "config": str(config_path),
        "lock": str(lock_path),
    }


def object_output_path(workspace: Path, document: dict[str, Any], layer: str, relative_path: Optional[str]) -> Path:
    if relative_path:
        return safe_workspace_path(workspace, relative_path)

    object_type = str(document.get("type", ""))
    object_id = str(document.get("id", ""))
    if not object_type or not object_id:
        raise HTTPException(status_code=400, detail="Document must declare id and type")
    default_layer, folder = OBJECT_TYPE_FOLDERS.get(object_type, ("catalog", "objects"))
    selected_layer = default_layer if layer == "auto" else layer
    if selected_layer not in {"catalog", "configurations"}:
        raise HTTPException(status_code=400, detail="Layer must be 'auto', 'catalog', or 'configurations'")
    if selected_layer != default_layer and object_type in {"compliance_framework", "compliance_profile", "domain", "object_patch", "odc"}:
        folder = OBJECT_TYPE_FOLDERS[object_type][1]
    return safe_workspace_path(workspace, f"{selected_layer}/{folder}/{slug(object_id)}.yaml")


def effective_model(workspace: Path) -> dict[str, Any]:
    base_config = FRAMEWORK_ROOT / "configurations"
    workspace_config = workspace / "configurations"
    workspace_catalog = workspace / "catalog"
    base_files = yaml_files(base_config, CONFIGURATION_FOLDERS)
    config_files = yaml_files(workspace_config, CONFIGURATION_FOLDERS)
    catalog_files = yaml_files(workspace_catalog, CATALOG_FOLDERS)
    objects: dict[str, dict[str, Any]] = {}
    for root, files, layer in (
        (base_config, base_files, "framework"),
        (workspace_config, config_files, "configuration"),
        (workspace_catalog, catalog_files, "catalog"),
    ):
        for path in files:
            row = object_row(path, root)
            row["layer"] = layer
            objects[str(row["id"])] = row
    objects = apply_object_patches(objects)
    return {
        "workspace": str(workspace),
        "layers": [
            {"name": "framework", "path": str(base_config), "count": len(base_files)},
            {"name": "configuration", "path": str(workspace_config), "count": len(config_files)},
            {"name": "catalog", "path": str(workspace_catalog), "count": len(catalog_files)},
        ],
        "objects": sorted(objects.values(), key=lambda item: str(item["id"])),
    }


@app.get("/")
def index():
    index_path = UI_ROOT / "index.html"
    if index_path.exists():
        return FileResponse(index_path)
    return {"message": "DRAFT App API", "docs": "/docs"}


@app.get("/assets/draftlogo.png")
def draft_logo() -> FileResponse:
    if not LOGO_PATH.exists():
        raise HTTPException(status_code=404, detail="DRAFT logo not found")
    return FileResponse(LOGO_PATH, media_type="image/png")


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/framework/manifest")
def framework_manifest() -> dict[str, Any]:
    return {
        "name": "DRAFT",
        "frameworkRoot": str(FRAMEWORK_ROOT),
        "schemaRoot": str(FRAMEWORK_ROOT / "schemas"),
        "configurationRoot": str(FRAMEWORK_ROOT / "configurations"),
        "tools": {
            "validate": "framework/tools/validate.py",
            "generateBrowser": "framework/tools/generate_browser.py",
            "generateAiIndex": "framework/tools/generate_ai_index.py",
        },
        "agentContract": {
            "effectiveModel": "/api/workspace/effective-model",
            "validate": "/api/workspace/validate",
            "gitStatus": "/api/git/status",
            "publish": "/api/publish",
            "draftsmanConfig": "/api/draftsman/config",
        },
    }


@app.get("/api/draftsman/providers")
def draftsman_providers() -> dict[str, Any]:
    return {
        "external": {
            "enabled": True,
            "description": "External AI agents use this repository, AGENTS.md, and the DRAFT App API from outside the app.",
        },
        "embedded": {
            "enabled": False,
            "allowedProviders": [
                {
                    "id": "openai",
                    "name": "OpenAI",
                    "auth": "oauth",
                    "apiKeysAllowed": False,
                    "status": "configuration-only",
                }
            ],
        },
    }


@app.get("/api/draftsman/config")
def draftsman_config(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    config_path = workspace_config_path(root)
    config = read_yaml(config_path) if config_path.exists() else {}
    draftsman = config.get("draftsman")
    if not isinstance(draftsman, dict):
        draftsman = draftsman_default_config()
    return {
        "workspace": str(root),
        "config": draftsman,
        "status": draftsman_config_status({"draftsman": draftsman}),
    }


@app.post("/api/draftsman/chat")
def draftsman_chat(request: DraftsmanChatRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    config_path = workspace_config_path(root)
    config = read_yaml(config_path) if config_path.exists() else {}
    status = draftsman_config_status(config)
    if not status["ok"]:
        raise HTTPException(status_code=400, detail=status)
    raise HTTPException(
        status_code=501,
        detail={
            "message": "Embedded AI Draftsman chat is not implemented in this version.",
            "status": status,
            "externalMode": "Use AGENTS.md, AI_INDEX.md, and /api/framework/manifest with an external AI agent.",
        },
    )


@app.get("/api/draftsman/oauth/openai/start")
def draftsman_openai_oauth_start() -> dict[str, Any]:
    raise HTTPException(
        status_code=501,
        detail={
            "message": "OpenAI OAuth for embedded Draftsman is configuration-only in this version.",
            "apiKeysAllowed": False,
        },
    )


@app.get("/api/draftsman/oauth/openai/callback")
def draftsman_openai_oauth_callback() -> dict[str, Any]:
    raise HTTPException(
        status_code=501,
        detail={
            "message": "OpenAI OAuth callback is not implemented in this version.",
            "apiKeysAllowed": False,
        },
    )


@app.get("/api/framework/updates")
def framework_updates(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    lock_path = root / ".draft" / "framework.lock"
    lock = read_yaml(lock_path) if lock_path.exists() else {}
    current = framework_pin()
    pinned = ((lock.get("framework") or {}).get("pinnedCommit") if isinstance(lock.get("framework"), dict) else "")
    return {
        "workspace": str(root),
        "lockPath": str(lock_path),
        "locked": lock,
        "currentFramework": current,
        "updateAvailable": bool(pinned and current.get("pinnedCommit") and pinned != current.get("pinnedCommit")),
        "note": "This compares the workspace lock to the running framework checkout. Remote update checks should use the configured GitHub integration.",
    }


@app.get("/api/workspace/config")
def workspace_config(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    config_path = workspace_config_path(root)
    if not config_path.exists():
        return {"workspace": str(root), "configured": False}
    return {"workspace": str(root), "configured": True, "config": read_yaml(config_path)}


@app.post("/api/workspace/init")
def workspace_init(request: WorkspaceInitRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace, must_exist=False)
    return initialize_workspace_files(root, request)


@app.put("/api/workspace/config")
def update_workspace_config(request: WorkspaceSettingsRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    config_path = workspace_config_path(root)
    write_yaml(config_path, request.config)
    return {"ok": True, "workspace": str(root), "path": str(config_path)}


@app.get("/api/workspace/effective-model")
def get_effective_model(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    return effective_model(resolve_workspace(workspace))


@app.get("/api/catalog/objects")
def catalog_objects(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    model = effective_model(resolve_workspace(workspace))
    return {"objects": [obj for obj in model["objects"] if obj.get("layer") == "catalog"]}


@app.post("/api/workspace/validate")
def validate_workspace(request: WorkspaceRequest) -> dict[str, Any]:
    return validate_workspace_result(resolve_workspace(request.workspace))


@app.post("/api/objects/upsert")
def upsert_object(request: ObjectWriteRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    document = dict(request.document)
    output_path = object_output_path(root, document, request.layer, request.path)
    write_yaml(output_path, document)
    result: dict[str, Any] = {
        "ok": True,
        "workspace": str(root),
        "path": output_path.relative_to(root).as_posix(),
        "id": document.get("id"),
        "type": document.get("type"),
    }
    if request.validateAfter:
        result["validation"] = validate_workspace_result(root)
    return result


@app.post("/api/object-patches/upsert")
def upsert_object_patch(request: ObjectPatchWriteRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    patch_id = f"patch.{slug(request.target)}.{slug(request.purpose)}"
    document: dict[str, Any] = {
        "schemaVersion": "1.0",
        "id": patch_id,
        "type": "object_patch",
        "name": request.name or f"{request.target} {request.purpose}",
        "description": request.description or "App-generated object patch.",
        "catalogStatus": request.catalogStatus,
        "lifecycleStatus": request.lifecycleStatus,
        "target": request.target,
        "patch": request.patch,
    }
    if request.owner:
        document["owner"] = request.owner
    if request.tags:
        document["tags"] = request.tags
    output_path = object_output_path(root, document, "configurations", None)
    write_yaml(output_path, document)
    result: dict[str, Any] = {
        "ok": True,
        "workspace": str(root),
        "path": output_path.relative_to(root).as_posix(),
        "id": patch_id,
        "target": request.target,
    }
    if request.validateAfter:
        result["validation"] = validate_workspace_result(root)
    return result


@app.get("/api/git/status")
def git_status(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    completed = run(["git", "status", "--short", "--branch"], root)
    return {"ok": completed.returncode == 0, "stdout": completed.stdout, "stderr": completed.stderr}


@app.post("/api/git/commit")
def git_commit(request: CommitRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    paths = request.paths or ["catalog", "configurations", ".draft"]
    add = run(["git", "add", *paths], root)
    if add.returncode != 0:
        return {"ok": False, "stage": "add", "stdout": add.stdout, "stderr": add.stderr}
    commit = run(["git", "commit", "-m", request.message], root)
    return {"ok": commit.returncode == 0, "stdout": commit.stdout, "stderr": commit.stderr}


@app.post("/api/git/push")
def git_push(request: PushRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    branch = request.branch
    if not branch:
        current = run(["git", "branch", "--show-current"], root)
        branch = current.stdout.strip() if current.returncode == 0 else "dev"
    completed = run(["git", "push", request.remote, branch], root)
    return {"ok": completed.returncode == 0, "stdout": completed.stdout, "stderr": completed.stderr}


@app.post("/api/publish")
def publish(request: PublishRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    if request.mode == "direct":
        completed = run(["git", "push", "origin", f"{request.head}:{request.base}"], root)
        return {"ok": completed.returncode == 0, "mode": "direct", "stdout": completed.stdout, "stderr": completed.stderr}
    completed = run(
        [
            "gh",
            "pr",
            "create",
            "--base",
            request.base,
            "--head",
            request.head,
            "--title",
            request.title,
            "--body",
            request.body,
        ],
        root,
    )
    return {"ok": completed.returncode == 0, "mode": "pull-request", "stdout": completed.stdout, "stderr": completed.stderr}


@app.get("/api/automation/readiness")
def automation_readiness(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    model = effective_model(resolve_workspace(workspace))
    candidates = [
        obj for obj in model["objects"]
        if obj.get("type") in {"rbb", "reference_architecture", "software_distribution_manifest"}
    ]
    return {
        "status": "informational",
        "message": "Automation readiness scoring is reserved for deployable architecture mappings.",
        "candidateCount": len(candidates),
        "candidates": candidates,
    }
