from __future__ import annotations

import base64
import copy
import hashlib
import html
import json
import os
import re
import secrets
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Optional

import yaml
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field


APP_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = APP_ROOT.parent
FRAMEWORK_ROOT = REPO_ROOT / "framework"
DEFAULT_WORKSPACE = REPO_ROOT / "examples"
UI_ROOT = APP_ROOT / "ui"
LOGO_PATH = REPO_ROOT / "draftlogo.png"
OPENAI_CODEX_CLIENT_ID = os.environ.get("DRAFT_OPENAI_CODEX_CLIENT_ID", "app_EMoamEEZ73f0CkXaXp7hrann")
OPENAI_CODEX_AUTH_URL = "https://auth.openai.com/oauth/authorize"
OPENAI_CODEX_TOKEN_URL = "https://auth.openai.com/oauth/token"
OPENAI_CODEX_API_BASE = os.environ.get("DRAFT_OPENAI_CODEX_API_BASE", "https://chatgpt.com/backend-api")
OPENAI_CODEX_REDIRECT_URI = os.environ.get("DRAFT_OPENAI_CODEX_REDIRECT_URI", "http://localhost:1455/auth/callback")
OPENAI_CODEX_CALLBACK_HOST = os.environ.get("DRAFT_OPENAI_CODEX_CALLBACK_HOST", "127.0.0.1")
OPENAI_CODEX_CALLBACK_PORT = int(os.environ.get("DRAFT_OPENAI_CODEX_CALLBACK_PORT", "1455"))
OPENAI_CODEX_SCOPE = "openid profile email offline_access"
AUTH_ROOT = Path(os.environ.get("DRAFT_AUTH_DIR", Path.home() / ".draft")).expanduser()
AUTH_STORE_PATH = AUTH_ROOT / "auth-profiles.json"
CODEX_AUTH_PATH = Path(os.environ.get("DRAFT_CODEX_AUTH_PATH", Path.home() / ".codex" / "auth.json")).expanduser()
AUTH_PROFILE_ID = "openai-codex"
AUTH_REFRESH_WINDOW_SECONDS = 300
OAUTH_PENDING: dict[str, dict[str, Any]] = {}
OAUTH_LOCK = threading.Lock()
OAUTH_CALLBACK_SERVER: ThreadingHTTPServer | None = None
OAUTH_CALLBACK_THREAD: threading.Thread | None = None

CATALOG_FOLDERS = (
    "abbs",
    "rbbs",
    "reference-architectures",
    "sdms",
    "product-services",
    "saas-services",
    "ards",
    "sessions",
    "objects",
)
CONFIGURATION_FOLDERS = (
    "odcs",
    "odc-overrides",
    "object-patches",
    "compliance-frameworks",
    "compliance-profiles",
    "object-types",
    "automation-targets",
    "domains",
)
OBJECT_TYPE_FOLDERS = {
    "abb": ("catalog", "abbs"),
    "ard": ("catalog", "ards"),
    "drafting_session": ("catalog", "sessions"),
    "rbb": ("catalog", "rbbs"),
    "reference_architecture": ("catalog", "reference-architectures"),
    "software_distribution_manifest": ("catalog", "sdms"),
    "compliance_framework": ("configurations", "compliance-frameworks"),
    "compliance_profile": ("configurations", "compliance-profiles"),
    "domain": ("configurations", "domains"),
    "object_patch": ("configurations", "object-patches"),
    "odc": ("configurations", "odc-overrides"),
}
ALLOWED_DRAFTSMAN_MODES = {"external", "embedded", "disabled"}
ALLOWED_EMBEDDED_PROVIDERS = {"openai"}
ALLOWED_EMBEDDED_AUTH_TYPES = {"oauth"}
DISALLOWED_SECRET_KEYS = {
    "accessToken",
    "access_token",
    "apiKey",
    "api_key",
    "apiKeyRef",
    "api_key_ref",
    "clientSecret",
    "client_secret",
    "idToken",
    "id_token",
    "openaiApiKey",
    "openai_api_key",
    "refreshToken",
    "refresh_token",
    "token",
}


class WorkspaceRequest(BaseModel):
    workspace: Optional[str] = Field(default=None, description="Workspace root path.")


class WorkspaceInitRequest(BaseModel):
    workspace: str
    name: Optional[str] = None
    repository: Optional[dict[str, Any]] = None
    framework: Optional[dict[str, Any]] = None


class WorkspaceSettingsRequest(WorkspaceRequest):
    config: dict[str, Any]


class DraftsmanConfigRequest(WorkspaceRequest):
    config: dict[str, Any]


class DraftsmanAuthCodeRequest(WorkspaceRequest):
    code: str
    state: str


class ObjectWriteRequest(WorkspaceRequest):
    document: dict[str, Any]
    layer: str = "auto"
    path: Optional[str] = None
    validateAfter: bool = True


class ObjectPatchWriteRequest(WorkspaceRequest):
    target: str
    patch: dict[str, Any]
    purpose: str = "override"
    name: Optional[str] = None
    description: Optional[str] = None
    owner: Optional[dict[str, Any]] = None
    tags: Optional[list[str]] = None
    catalogStatus: str = "draft"
    lifecycleStatus: str = "invest"
    validateAfter: bool = True


class CommitRequest(WorkspaceRequest):
    message: str
    paths: Optional[list[str]] = None


class PushRequest(WorkspaceRequest):
    remote: str = "origin"
    branch: Optional[str] = None


class PublishRequest(WorkspaceRequest):
    base: Optional[str] = None
    head: Optional[str] = None
    title: str = "Publish DRAFT catalog updates"
    body: str = "Generated by the DRAFT App."
    mode: Optional[str] = None


class DraftsmanChatRequest(WorkspaceRequest):
    message: str
    contextObjectId: Optional[str] = None
    attachments: Optional[list[dict[str, Any]]] = None


app = FastAPI(
    title="DRAFT App API",
    version="0.1.0",
    description="API-first surface for DRAFT workspaces, UI clients, and AI agents.",
)

if UI_ROOT.exists():
    app.mount("/ui", StaticFiles(directory=UI_ROOT), name="ui")


def run(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            cwd=str(cwd),
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise HTTPException(status_code=500, detail=f"Command not available: {command[0]}") from exc


def resolve_workspace(workspace: Optional[str] = None, must_exist: bool = True) -> Path:
    # Handle both None and empty strings from JSON bodies
    workspace_str = (workspace or "").strip()
    raw = workspace_str or os.environ.get("DRAFT_WORKSPACE") or str(DEFAULT_WORKSPACE)
    
    # Normalize Windows paths
    root = Path(raw).expanduser().resolve()
    
    if must_exist and not root.exists():
        # Log the exact path that failed to help debug Windows resolution
        print(f"DEBUG: Workspace not found. raw='{raw}', resolved='{root}'")
        raise HTTPException(status_code=404, detail=f"Workspace does not exist: {root}")
    return root


@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    import traceback
    if isinstance(exc, HTTPException):
        print(f"DEBUG: HTTPException {exc.status_code}: {exc.detail}")
        return await app.default_exception_handler(request, exc)
    
    print(f"DEBUG: Unhandled error: {exc}")
    traceback.print_exc()
    return HTTPException(status_code=500, detail=str(exc))


def workspace_config_path(workspace: Path) -> Path:
    return workspace / ".draft" / "workspace.yaml"


def read_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    return data if isinstance(data, dict) else {}


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(data, handle, sort_keys=False, allow_unicode=False)


def write_json_private(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        path.parent.chmod(0o700)
    except OSError:
        pass
    with path.open("w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2)
        handle.write("\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    return data if isinstance(data, dict) else {}


def base64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def pkce_verifier() -> str:
    return base64url(secrets.token_bytes(48))


def pkce_challenge(verifier: str) -> str:
    return base64url(hashlib.sha256(verifier.encode("ascii")).digest())


def now_epoch() -> int:
    return int(time.time())


def iso_from_epoch(value: int | float | None) -> str:
    if not value:
        return ""
    return datetime.fromtimestamp(float(value), timezone.utc).replace(microsecond=0).isoformat()


def parse_jwt_payload(token: str | None) -> dict[str, Any]:
    if not token or token.count(".") < 2:
        return {}
    payload = token.split(".")[1]
    payload += "=" * (-len(payload) % 4)
    try:
        decoded = base64.urlsafe_b64decode(payload.encode("ascii"))
        data = json.loads(decoded.decode("utf-8"))
    except (ValueError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def auth_claims(tokens: dict[str, Any]) -> dict[str, Any]:
    payload = parse_jwt_payload(str(tokens.get("access_token") or tokens.get("accessToken") or ""))
    id_payload = parse_jwt_payload(str(tokens.get("id_token") or tokens.get("idToken") or ""))
    auth = payload.get("https://api.openai.com/auth")
    profile = payload.get("https://api.openai.com/profile")
    if not isinstance(auth, dict):
        auth = {}
    if not isinstance(profile, dict):
        profile = {}
    id_auth = id_payload.get("https://api.openai.com/auth")
    if isinstance(id_auth, dict):
        auth = {**id_auth, **auth}
    return {
        "accountId": auth.get("chatgpt_account_id") or tokens.get("account_id") or tokens.get("accountId") or "",
        "accountUserId": auth.get("chatgpt_account_user_id") or "",
        "chatgptUserId": auth.get("chatgpt_user_id") or auth.get("user_id") or "",
        "planType": auth.get("chatgpt_plan_type") or "",
        "email": profile.get("email") or id_payload.get("email") or "",
        "subject": payload.get("sub") or id_payload.get("sub") or "",
    }


def auth_store() -> dict[str, Any]:
    data = read_json(AUTH_STORE_PATH)
    if not data:
        data = {"schemaVersion": "1.0", "profiles": {}}
    if not isinstance(data.get("profiles"), dict):
        data["profiles"] = {}
    return data


def read_auth_profile() -> dict[str, Any] | None:
    profile = auth_store().get("profiles", {}).get(AUTH_PROFILE_ID)
    return profile if isinstance(profile, dict) else None


def save_auth_profile(tokens: dict[str, Any], source: str = "draft-oauth") -> dict[str, Any]:
    access_token = str(tokens.get("access_token") or tokens.get("accessToken") or "")
    refresh_token = str(tokens.get("refresh_token") or tokens.get("refreshToken") or "")
    id_token = str(tokens.get("id_token") or tokens.get("idToken") or "")
    expires_in = int(tokens.get("expires_in") or tokens.get("expiresIn") or 3600)
    expires_at = int(tokens.get("expiresAtEpoch") or (now_epoch() + expires_in))
    claims = auth_claims(
        {
            "access_token": access_token,
            "refresh_token": refresh_token,
            "id_token": id_token,
            "account_id": tokens.get("account_id") or tokens.get("accountId") or "",
        }
    )
    profile = {
        "provider": "openai-codex",
        "authType": "chatgpt-codex-oauth",
        "source": source,
        "accessToken": access_token,
        "refreshToken": refresh_token,
        "idToken": id_token,
        "expiresAtEpoch": expires_at,
        "expiresAt": iso_from_epoch(expires_at),
        "accountId": claims["accountId"],
        "accountUserId": claims["accountUserId"],
        "chatgptUserId": claims["chatgptUserId"],
        "planType": claims["planType"],
        "email": claims["email"],
        "subject": claims["subject"],
        "updatedAt": now_iso(),
    }
    store = auth_store()
    store["profiles"][AUTH_PROFILE_ID] = profile
    write_json_private(AUTH_STORE_PATH, store)
    return profile


def delete_auth_profile() -> bool:
    store = auth_store()
    existed = AUTH_PROFILE_ID in store.get("profiles", {})
    store.get("profiles", {}).pop(AUTH_PROFILE_ID, None)
    write_json_private(AUTH_STORE_PATH, store)
    return existed


def openai_codex_auth_status() -> dict[str, Any]:
    profile = read_auth_profile()
    if not profile:
        return {
            "signedIn": False,
            "provider": "openai-codex",
            "authType": "chatgpt-codex-oauth",
            "tokenStore": str(AUTH_STORE_PATH),
            "callbackUrl": OPENAI_CODEX_REDIRECT_URI,
            "accountId": "",
            "email": "",
            "planType": "",
            "expiresAt": "",
        }
    expires_at = int(profile.get("expiresAtEpoch") or 0)
    return {
        "signedIn": bool(profile.get("accessToken") and profile.get("refreshToken")),
        "provider": "openai-codex",
        "authType": "chatgpt-codex-oauth",
        "tokenStore": str(AUTH_STORE_PATH),
        "callbackUrl": OPENAI_CODEX_REDIRECT_URI,
        "accountId": profile.get("accountId", ""),
        "email": profile.get("email", ""),
        "planType": profile.get("planType", ""),
        "source": profile.get("source", ""),
        "expiresAt": profile.get("expiresAt") or iso_from_epoch(expires_at),
        "expiresSoon": bool(expires_at and expires_at - now_epoch() <= AUTH_REFRESH_WINDOW_SECONDS),
    }


def oauth_token_request(payload: dict[str, str]) -> dict[str, Any]:
    body = urllib.parse.urlencode(payload).encode("utf-8")
    request = urllib.request.Request(
        OPENAI_CODEX_TOKEN_URL,
        data=body,
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "application/json",
            "User-Agent": "DRAFT-App/0.1",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            data = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise HTTPException(status_code=exc.code, detail=detail) from exc
    except urllib.error.URLError as exc:
        raise HTTPException(status_code=502, detail=f"OpenAI OAuth token exchange failed: {exc.reason}") from exc
    parsed = json.loads(data)
    return parsed if isinstance(parsed, dict) else {}


def exchange_openai_codex_code(code: str, verifier: str) -> dict[str, Any]:
    return oauth_token_request(
        {
            "grant_type": "authorization_code",
            "client_id": OPENAI_CODEX_CLIENT_ID,
            "code": code,
            "code_verifier": verifier,
            "redirect_uri": OPENAI_CODEX_REDIRECT_URI,
        }
    )


def refresh_openai_codex_tokens(profile: dict[str, Any]) -> dict[str, Any]:
    refresh_token = str(profile.get("refreshToken") or "")
    if not refresh_token:
        raise HTTPException(status_code=401, detail="No OpenAI Codex refresh token is available. Sign in again.")
    tokens = oauth_token_request(
        {
            "grant_type": "refresh_token",
            "client_id": OPENAI_CODEX_CLIENT_ID,
            "refresh_token": refresh_token,
        }
    )
    if not tokens.get("refresh_token"):
        tokens["refresh_token"] = refresh_token
    if not tokens.get("id_token") and profile.get("idToken"):
        tokens["id_token"] = profile["idToken"]
    return save_auth_profile(tokens, source=str(profile.get("source") or "draft-oauth"))


def active_openai_codex_profile() -> dict[str, Any]:
    profile = read_auth_profile()
    if not profile or not profile.get("accessToken"):
        raise HTTPException(status_code=401, detail="OpenAI Codex sign-in required.")
    expires_at = int(profile.get("expiresAtEpoch") or 0)
    if expires_at and expires_at - now_epoch() <= AUTH_REFRESH_WINDOW_SECONDS:
        profile = refresh_openai_codex_tokens(profile)
    return profile


def import_codex_cli_auth() -> dict[str, Any]:
    data = read_json(CODEX_AUTH_PATH)
    tokens = data.get("tokens")
    if not isinstance(tokens, dict):
        raise HTTPException(status_code=404, detail=f"Codex CLI auth was not found at {CODEX_AUTH_PATH}")
    normalized = {
        "access_token": tokens.get("access_token", ""),
        "refresh_token": tokens.get("refresh_token", ""),
        "id_token": tokens.get("id_token", ""),
        "account_id": tokens.get("account_id", ""),
    }
    access_claims = parse_jwt_payload(str(normalized["access_token"]))
    if access_claims.get("exp"):
        normalized["expiresAtEpoch"] = int(access_claims["exp"])
    return save_auth_profile(normalized, source="codex-cli-import")


def extract_response_text(value: Any) -> str:
    parts: list[str] = []

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            node_type = node.get("type")
            if node_type in {"output_text", "text"} and isinstance(node.get("text"), str):
                parts.append(node["text"])
            elif isinstance(node.get("content"), list):
                visit(node["content"])
            elif isinstance(node.get("output"), list):
                visit(node["output"])
            elif isinstance(node.get("message"), dict):
                visit(node["message"])
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(value)
    return "\n".join(part for part in parts if part).strip()


def stream_chatgpt_codex_response(payload: dict[str, Any], profile: dict[str, Any]) -> dict[str, Any]:
    account_id = str(profile.get("accountId") or "")
    headers = {
        "Authorization": f"Bearer {profile['accessToken']}",
        "Content-Type": "application/json",
        "Accept": "text/event-stream",
        "User-Agent": "DRAFT-App/0.1",
        "OpenAI-Beta": "responses_websockets=2026-02-06",
        "x-responsesapi-include-timing-metrics": "true",
        "x-codex-installation-id": "draft-app",
        "originator": "draft-app",
    }
    if account_id:
        headers["ChatGPT-Account-Id"] = account_id
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        f"{OPENAI_CODEX_API_BASE.rstrip('/')}/responses",
        data=body,
        headers=headers,
        method="POST",
    )
    text_parts: list[str] = []
    final_response: dict[str, Any] = {}
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            for raw_line in response:
                line = raw_line.decode("utf-8", errors="replace").strip()
                if not line.startswith("data:"):
                    continue
                data = line.removeprefix("data:").strip()
                if not data or data == "[DONE]":
                    continue
                try:
                    event = json.loads(data)
                except json.JSONDecodeError:
                    continue
                event_type = event.get("type")
                delta = event.get("delta")
                if event_type == "response.output_text.delta" and isinstance(delta, str):
                    text_parts.append(delta)
                if event_type == "response.completed" and isinstance(event.get("response"), dict):
                    final_response = event["response"]
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise HTTPException(status_code=exc.code, detail=detail) from exc
    except urllib.error.URLError as exc:
        raise HTTPException(status_code=502, detail=f"OpenAI Codex response failed: {exc.reason}") from exc
    text = "".join(text_parts).strip() or extract_response_text(final_response)
    return {
        "text": text,
        "response": final_response,
    }


class OpenAICodexCallbackHandler(BaseHTTPRequestHandler):
    def log_message(self, format: str, *args: Any) -> None:
        return

    def do_GET(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path != "/auth/callback":
            self.send_error(404)
            return
        params = urllib.parse.parse_qs(parsed.query)
        state = (params.get("state") or [""])[0]
        code = (params.get("code") or [""])[0]
        error = (params.get("error") or [""])[0]
        try:
            result = complete_openai_codex_oauth(state, code, error)
            ok = result.get("ok", False)
            title = "DRAFT sign-in complete" if ok else "DRAFT sign-in failed"
            detail = "You can close this window and return to DRAFT." if ok else str(result.get("error", "Sign-in failed."))
        except Exception as exc:  # Callback must return a readable browser page.
            ok = False
            title = "DRAFT sign-in failed"
            detail = str(exc)
        safe_title = html.escape(title)
        safe_detail = html.escape(detail)
        html = f"""<!doctype html>
<html><head><title>{safe_title}</title><style>
body{{font-family:system-ui,sans-serif;background:#101215;color:#e7edf4;margin:40px;line-height:1.5}}
.panel{{max-width:680px;border:1px solid #334155;border-radius:8px;padding:24px;background:#171a1f}}
.ok{{color:#73d18b}}.err{{color:#f97066}}
</style></head><body><div class="panel">
<h1 class="{'ok' if ok else 'err'}">{safe_title}</h1><p>{safe_detail}</p>
</div></body></html>"""
        encoded = html.encode("utf-8")
        self.send_response(200 if ok else 400)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)


def ensure_openai_codex_callback_server() -> None:
    global OAUTH_CALLBACK_SERVER, OAUTH_CALLBACK_THREAD
    if OAUTH_CALLBACK_SERVER and OAUTH_CALLBACK_THREAD and OAUTH_CALLBACK_THREAD.is_alive():
        return
    try:
        OAUTH_CALLBACK_SERVER = ThreadingHTTPServer(
            (OPENAI_CODEX_CALLBACK_HOST, OPENAI_CODEX_CALLBACK_PORT),
            OpenAICodexCallbackHandler,
        )
    except OSError as exc:
        raise HTTPException(
            status_code=409,
            detail=f"Could not start local OAuth callback listener on {OPENAI_CODEX_CALLBACK_HOST}:{OPENAI_CODEX_CALLBACK_PORT}: {exc}",
        ) from exc
    OAUTH_CALLBACK_THREAD = threading.Thread(target=OAUTH_CALLBACK_SERVER.serve_forever, daemon=True)
    OAUTH_CALLBACK_THREAD.start()


def complete_openai_codex_oauth(state: str, code: str, error: str = "") -> dict[str, Any]:
    if error:
        return {"ok": False, "error": error}
    if not state or not code:
        return {"ok": False, "error": "OAuth callback was missing state or code."}
    with OAUTH_LOCK:
        pending = OAUTH_PENDING.pop(state, None)
    if not pending:
        return {"ok": False, "error": "OAuth state was not recognized or already used."}
    if pending.get("expiresAtEpoch", 0) < now_epoch():
        return {"ok": False, "error": "OAuth state expired. Start sign-in again."}
    tokens = exchange_openai_codex_code(code, str(pending["verifier"]))
    profile = save_auth_profile(tokens, source="draft-oauth")
    return {"ok": True, "profile": auth_profile_public(profile)}


def auth_profile_public(profile: dict[str, Any]) -> dict[str, Any]:
    return {
        "provider": profile.get("provider", "openai-codex"),
        "authType": profile.get("authType", "chatgpt-codex-oauth"),
        "source": profile.get("source", ""),
        "accountId": profile.get("accountId", ""),
        "email": profile.get("email", ""),
        "planType": profile.get("planType", ""),
        "expiresAt": profile.get("expiresAt", ""),
    }


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9.-]+", "-", value.lower()).strip(".-") or "object"


def safe_workspace_path(workspace: Path, relative_path: str) -> Path:
    candidate = (workspace / relative_path).resolve()
    if not candidate.is_relative_to(workspace.resolve()):
        raise HTTPException(status_code=400, detail="Path must stay inside the workspace")
    return candidate


def yaml_files(root: Path, folders: tuple[str, ...]) -> list[Path]:
    files: list[Path] = []
    for folder in folders:
        candidate = root / folder
        if candidate.exists():
            files.extend(sorted(candidate.rglob("*.yaml")))
    return files


def object_row(path: Path, root: Path) -> dict[str, Any]:
    data = read_yaml(path)
    row = dict(data)
    row.setdefault("id", path.stem)
    row.setdefault("name", path.stem)
    row.setdefault("type", "yaml")
    row["source"] = path.relative_to(root).as_posix() if path.is_relative_to(root) else path.as_posix()
    return row


def deep_merge(base: Any, patch: Any) -> Any:
    if isinstance(base, dict) and isinstance(patch, dict):
        merged = copy.deepcopy(base)
        for key, value in patch.items():
            if key in {"id", "type"}:
                continue
            merged[key] = deep_merge(merged.get(key), value)
        return merged
    return copy.deepcopy(patch)


def apply_object_patches(objects: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    patched = dict(objects)
    for obj in objects.values():
        if obj.get("type") != "object_patch":
            continue
        target_id = str(obj.get("target", ""))
        patch = obj.get("patch")
        if target_id and target_id in patched and isinstance(patch, dict):
            patched[target_id] = deep_merge(patched[target_id], patch)
    return patched


def validate_workspace_result(workspace: Path) -> dict[str, Any]:
    completed = run([sys.executable, str(FRAMEWORK_ROOT / "tools" / "validate.py"), "--workspace", str(workspace)], REPO_ROOT)
    return {
        "ok": completed.returncode == 0,
        "returnCode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def workspace_repository_config(workspace: Path) -> dict[str, Any]:
    config_path = workspace_config_path(workspace)
    config = read_yaml(config_path) if config_path.exists() else {}
    repository = config.get("repository")
    if not isinstance(repository, dict):
        repository = {}
    return {
        "defaultBranch": repository.get("defaultBranch") or "main",
        "devBranch": repository.get("devBranch") or "draft-dev",
        "publishMode": repository.get("publishMode") or "pull-request",
    }


def git_stdout(command: list[str], cwd: Path) -> str:
    completed = run(command, cwd)
    if completed.returncode != 0:
        raise HTTPException(status_code=500, detail=completed.stderr or completed.stdout or f"Command failed: {' '.join(command)}")
    return completed.stdout.strip()


def ensure_working_branch(workspace: Path) -> str:
    repo = workspace_repository_config(workspace)
    default_branch = str(repo["defaultBranch"])
    dev_branch = str(repo["devBranch"])
    current = run(["git", "branch", "--show-current"], workspace)
    branch = current.stdout.strip() if current.returncode == 0 else ""
    if branch and branch != default_branch:
        return branch
    if not dev_branch:
        raise HTTPException(status_code=400, detail="repository.devBranch is required for app-managed writes")
    remote = run(["git", "show-ref", "--verify", "--quiet", f"refs/remotes/origin/{dev_branch}"], workspace)
    if remote.returncode == 0:
        git_stdout(["git", "checkout", dev_branch], workspace)
    else:
        git_stdout(["git", "checkout", "-B", dev_branch], workspace)
    return dev_branch


def framework_pin() -> dict[str, str]:
    commit = run(["git", "rev-parse", "HEAD"], REPO_ROOT)
    return {
        "source": "https://github.com/dsackr/draft-framework.git",
        "pinnedRef": "main",
        "pinnedCommit": commit.stdout.strip() if commit.returncode == 0 else "",
    }


def draftsman_default_config() -> dict[str, Any]:
    return {
        "mode": "external",
        "external": {
            "enabled": True,
            "description": "Use an external AI agent with AGENTS.md, AI_INDEX.md, and the DRAFT App API.",
            "entrypoints": [
                "AGENTS.md",
                "AI_INDEX.md",
                "framework/docs/draftsman.md",
                "app/api",
            ],
        },
        "embedded": {
            "enabled": False,
            "provider": "openai",
            "model": "gpt-5.5",
            "auth": {
                "type": "oauth",
                "clientId": OPENAI_CODEX_CLIENT_ID,
                "redirectUri": OPENAI_CODEX_REDIRECT_URI,
                "tokenStorage": "user-local",
                "apiKeysAllowed": False,
            },
        },
        "security": {
            "storeSecretsInWorkspace": False,
            "sendGitCredentialsToModel": False,
            "writeRequiresAppValidation": True,
        },
    }


def normalize_draftsman_config(config: Any) -> dict[str, Any]:
    if not isinstance(config, dict):
        config = {}
    return deep_merge(draftsman_default_config(), config)


def find_disallowed_secret_keys(node: Any, path: str = "draftsman") -> list[str]:
    matches: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            next_path = f"{path}.{key}"
            if key in DISALLOWED_SECRET_KEYS:
                matches.append(next_path)
            matches.extend(find_disallowed_secret_keys(value, next_path))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            matches.extend(find_disallowed_secret_keys(value, f"{path}[{index}]"))
    return matches


def draftsman_config_status(config: dict[str, Any]) -> dict[str, Any]:
    draftsman = config.get("draftsman")
    if not isinstance(draftsman, dict):
        draftsman = draftsman_default_config()
    draftsman = normalize_draftsman_config(draftsman)

    issues: list[str] = []
    mode = draftsman.get("mode", "external")
    if mode not in ALLOWED_DRAFTSMAN_MODES:
        issues.append(f"draftsman.mode must be one of {sorted(ALLOWED_DRAFTSMAN_MODES)}")

    embedded = draftsman.get("embedded", {})
    if not isinstance(embedded, dict):
        embedded = {}
    provider = embedded.get("provider", "openai")
    if provider not in ALLOWED_EMBEDDED_PROVIDERS:
        issues.append("Only OpenAI is allowed as an embedded Draftsman provider in this version")

    auth = embedded.get("auth", {})
    if not isinstance(auth, dict):
        auth = {}
    auth_type = auth.get("type", "oauth")
    if auth_type not in ALLOWED_EMBEDDED_AUTH_TYPES:
        issues.append("Only OAuth is allowed for embedded Draftsman auth; API keys are not allowed")
    if auth.get("apiKeysAllowed") is not False:
        issues.append("draftsman.embedded.auth.apiKeysAllowed must remain false")
    if auth.get("tokenStorage") in {"workspace", "file", "files"}:
        issues.append("OAuth tokens must not be stored in workspace files")

    secret_keys = find_disallowed_secret_keys(draftsman)
    if secret_keys:
        issues.append(f"Workspace config must not contain secret fields: {', '.join(secret_keys)}")

    auth_status = openai_codex_auth_status()
    embedded_available = bool(mode == "embedded" and auth_status["signedIn"])
    return {
        "ok": not issues,
        "mode": mode,
        "embeddedProvider": provider,
        "embeddedAuth": auth_type,
        "externalAgentAvailable": mode in {"external", "embedded"},
        "embeddedDraftsmanAvailable": embedded_available,
        "embeddedImplementationStatus": "available" if embedded_available else "sign-in-required",
        "oauthRuntimeConfigured": auth_status["signedIn"],
        "oauthClientId": auth.get("clientId", OPENAI_CODEX_CLIENT_ID),
        "oauthRedirectUri": auth.get("redirectUri", ""),
        "auth": auth_status,
        "issues": issues,
        "note": "Embedded Draftsman uses the signed-in user's ChatGPT/Codex OAuth session. Tokens are stored outside the workspace repo.",
    }


def workspace_defaults(root: Path, request: WorkspaceInitRequest) -> tuple[dict[str, Any], dict[str, Any]]:
    framework = framework_pin()
    framework.update(request.framework or {})
    config = {
        "schemaVersion": "1.0",
        "workspace": {
            "name": request.name or root.name,
            "mode": "shared-app",
        },
        "repository": {
            "provider": "github",
            "owner": "",
            "name": root.name,
            "defaultBranch": "main",
            "devBranch": "dev",
            "publishMode": "pull-request",
        },
        "framework": framework,
        "paths": {
            "catalog": "catalog",
            "configurations": "configurations",
        },
        "auth": {
            "localMode": "gh",
            "sharedAppMode": "github-app",
        },
        "draftsman": draftsman_default_config(),
    }
    if request.repository:
        config["repository"].update(request.repository)
    lock = {
        "schemaVersion": "1.0",
        "framework": {
            **framework,
            "updatedAt": now_iso(),
        },
    }
    return config, lock


def initialize_workspace_files(root: Path, request: WorkspaceInitRequest) -> dict[str, Any]:
    root.mkdir(parents=True, exist_ok=True)
    for folder in CATALOG_FOLDERS:
        (root / "catalog" / folder).mkdir(parents=True, exist_ok=True)
    for folder in CONFIGURATION_FOLDERS:
        (root / "configurations" / folder).mkdir(parents=True, exist_ok=True)
    (root / ".draft").mkdir(parents=True, exist_ok=True)

    config, lock = workspace_defaults(root, request)
    config_path = root / ".draft" / "workspace.yaml"
    lock_path = root / ".draft" / "framework.lock"
    if not config_path.exists():
        write_yaml(config_path, config)
    if not lock_path.exists():
        write_yaml(lock_path, lock)
    return {
        "workspace": str(root),
        "created": True,
        "config": str(config_path),
        "lock": str(lock_path),
    }


def object_output_path(workspace: Path, document: dict[str, Any], layer: str, relative_path: Optional[str]) -> Path:
    if relative_path:
        return safe_workspace_path(workspace, relative_path)

    object_type = str(document.get("type", ""))
    object_id = str(document.get("id", ""))
    if not object_type or not object_id:
        raise HTTPException(status_code=400, detail="Document must declare id and type")
    default_layer, folder = OBJECT_TYPE_FOLDERS.get(object_type, ("catalog", "objects"))
    selected_layer = default_layer if layer == "auto" else layer
    if selected_layer not in {"catalog", "configurations"}:
        raise HTTPException(status_code=400, detail="Layer must be 'auto', 'catalog', or 'configurations'")
    if selected_layer != default_layer and object_type in {"compliance_framework", "compliance_profile", "domain", "object_patch", "odc"}:
        folder = OBJECT_TYPE_FOLDERS[object_type][1]
    return safe_workspace_path(workspace, f"{selected_layer}/{folder}/{slug(object_id)}.yaml")


def effective_model(workspace: Path) -> dict[str, Any]:
    base_config = FRAMEWORK_ROOT / "configurations"
    workspace_config = workspace / "configurations"
    workspace_catalog = workspace / "catalog"
    base_files = yaml_files(base_config, CONFIGURATION_FOLDERS)
    config_files = yaml_files(workspace_config, CONFIGURATION_FOLDERS)
    catalog_files = yaml_files(workspace_catalog, CATALOG_FOLDERS)
    objects: dict[str, dict[str, Any]] = {}
    for root, files, layer in (
        (base_config, base_files, "framework"),
        (workspace_config, config_files, "configuration"),
        (workspace_catalog, catalog_files, "catalog"),
    ):
        for path in files:
            row = object_row(path, root)
            row["layer"] = layer
            objects[str(row["id"])] = row
    objects = apply_object_patches(objects)
    return {
        "workspace": str(workspace),
        "layers": [
            {"name": "framework", "path": str(base_config), "count": len(base_files)},
            {"name": "configuration", "path": str(workspace_config), "count": len(config_files)},
            {"name": "catalog", "path": str(workspace_catalog), "count": len(catalog_files)},
        ],
        "objects": sorted(objects.values(), key=lambda item: str(item["id"])),
    }


def draftsman_context(workspace: Path, context_object_id: Optional[str]) -> str:
    model = effective_model(workspace)
    objects = model.get("objects", [])
    selected = None
    if context_object_id:
        selected = next((obj for obj in objects if obj.get("id") == context_object_id), None)
    object_rows = [
        {
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "layer": obj.get("layer"),
            "source": obj.get("source"),
        }
        for obj in objects[:120]
    ]
    context = {
        "workspace": str(workspace),
        "framework": "DRAFT",
        "selectedObject": selected,
        "objectCount": len(objects),
        "objects": object_rows,
        "rules": [
            "Act as The Draftsman for DRAFT architecture content.",
            "Ask concise follow-up questions when ODC or compliance evidence is missing.",
            "Do not claim to write files directly; propose changes that the app/API can validate and write.",
            "Never ask for, reveal, or store API keys, OAuth tokens, Git credentials, or other secrets.",
            "Prefer reusable off-the-shelf catalog artifacts before creating new objects.",
        ],
    }
    return json.dumps(context, indent=2)


def call_embedded_draftsman(root: Path, config: dict[str, Any], request: DraftsmanChatRequest) -> dict[str, Any]:
    draftsman = normalize_draftsman_config(config.get("draftsman") if isinstance(config, dict) else {})
    model = str(((draftsman.get("embedded") or {}).get("model") or "gpt-5.5"))
    profile = active_openai_codex_profile()
    instructions = (
        "You are The Draftsman inside the DRAFT App. "
        "Help users document deployable architecture in the DRAFT framework. "
        "Use the provided effective-model context as source material. "
        "Be direct, ask needed questions, and produce concrete object or patch recommendations. "
        "Do not expose secrets and do not claim you have written files unless the app/API reports that action."
    )
    content: list[dict[str, Any]] = [
        {
            "type": "input_text",
            "text": f"Effective DRAFT context:\n{draftsman_context(root, request.contextObjectId)}\n\nUser request:\n{request.message}",
        }
    ]
    for attachment in request.attachments or []:
        if not isinstance(attachment, dict):
            continue
        name = str(attachment.get("name") or "attachment")
        media_type = str(attachment.get("type") or "")
        text = attachment.get("text")
        data_url = attachment.get("dataUrl")
        if media_type.startswith("image/") and isinstance(data_url, str) and data_url.startswith("data:image/"):
            content.append({"type": "input_image", "image_url": data_url})
            content.append({"type": "input_text", "text": f"Uploaded image: {name}"})
        elif isinstance(text, str):
            content.append({"type": "input_text", "text": f"Uploaded text file {name}:\n{text[:12000]}"})

    payload = {
        "model": model,
        "stream": True,
        "store": False,
        "instructions": instructions,
        "input": [
            {
                "role": "user",
                "content": content,
            }
        ],
    }
    response = stream_chatgpt_codex_response(payload, profile)
    return {
        "ok": True,
        "mode": "embedded",
        "provider": "openai-codex",
        "model": model,
        "account": auth_profile_public(profile),
        "message": response["text"],
    }


@app.get("/")
def index():
    index_path = UI_ROOT / "index.html"
    if index_path.exists():
        return FileResponse(index_path)
    return {"message": "DRAFT App API", "docs": "/docs"}


@app.get("/assets/draftlogo.png")
def draft_logo() -> FileResponse:
    if not LOGO_PATH.exists():
        raise HTTPException(status_code=404, detail="DRAFT logo not found")
    return FileResponse(LOGO_PATH, media_type="image/png")


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/diagnostics/routes")
def diagnostics_routes() -> dict[str, Any]:
    routes = []
    for route in app.routes:
        path = getattr(route, "path", "")
        methods = sorted(getattr(route, "methods", []) or [])
        if path:
            routes.append({"path": path, "methods": methods})
            
    # Redact potential secrets from environment
    safe_env = {}
    for key, value in os.environ.items():
        if any(secret in key.lower() for secret in ["key", "token", "secret", "auth", "pwd", "password"]):
            safe_env[key] = "[REDACTED]"
        else:
            safe_env[key] = value

    return {
        "mainFile": __file__,
        "appRoot": str(APP_ROOT),
        "repoRoot": str(REPO_ROOT),
        "frameworkRoot": str(FRAMEWORK_ROOT),
        "sysPath": sys.path,
        "env": safe_env,
        "routes": routes,
        "draftsmanRoutes": [route for route in routes if "draft" in route["path"]],
    }


@app.get("/api/framework/manifest")
def framework_manifest() -> dict[str, Any]:
    return {
        "name": "DRAFT",
        "frameworkRoot": str(FRAMEWORK_ROOT),
        "schemaRoot": str(FRAMEWORK_ROOT / "schemas"),
        "configurationRoot": str(FRAMEWORK_ROOT / "configurations"),
        "tools": {
            "validate": "framework/tools/validate.py",
            "generateBrowser": "framework/tools/generate_browser.py",
            "generateAiIndex": "framework/tools/generate_ai_index.py",
        },
        "agentContract": {
            "effectiveModel": "/api/workspace/effective-model",
            "validate": "/api/workspace/validate",
            "gitStatus": "/api/git/status",
            "publish": "/api/publish",
            "draftsmanConfig": "/api/draftsman/config",
        },
    }


@app.get("/api/draftsman/providers")
def draftsman_providers() -> dict[str, Any]:
    return {
        "external": {
            "enabled": True,
            "description": "External AI agents use this repository, AGENTS.md, and the DRAFT App API from outside the app.",
        },
        "embedded": {
            "enabled": True,
            "runtimeAvailable": openai_codex_auth_status()["signedIn"],
            "status": "available-after-user-sign-in",
            "description": "Each local user signs in with ChatGPT/Codex OAuth. Tokens are stored under the user's home directory, not in the workspace repo.",
            "allowedProviders": [
                {
                    "id": "openai",
                    "name": "OpenAI",
                    "auth": "oauth",
                    "apiKeysAllowed": False,
                    "status": "available-after-user-sign-in",
                    "clientIdDefault": OPENAI_CODEX_CLIENT_ID,
                    "redirectUriDefault": OPENAI_CODEX_REDIRECT_URI,
                    "tokenStorage": str(AUTH_STORE_PATH),
                }
            ],
        },
    }


@app.get("/api/draftsman/config")
def draftsman_config(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    config_path = workspace_config_path(root)
    config = read_yaml(config_path) if config_path.exists() else {}
    draftsman = config.get("draftsman")
    if not isinstance(draftsman, dict):
        draftsman = draftsman_default_config()
    draftsman = normalize_draftsman_config(draftsman)
    return {
        "workspace": str(root),
        "config": draftsman,
        "status": draftsman_config_status({"draftsman": draftsman}),
    }


@app.put("/api/draftsman/config")
def update_draftsman_config(request: DraftsmanConfigRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    config_path = workspace_config_path(root)
    workspace_config = read_yaml(config_path) if config_path.exists() else {}
    draftsman = normalize_draftsman_config(request.config)
    status = draftsman_config_status({"draftsman": draftsman})
    if not status["ok"]:
        raise HTTPException(status_code=400, detail=status)
    workspace_config["draftsman"] = draftsman
    write_yaml(config_path, workspace_config)
    return {
        "ok": True,
        "workspace": str(root),
        "path": str(config_path),
        "config": draftsman,
        "status": status,
    }


@app.post("/api/draftsman/chat")
def draftsman_chat(request: DraftsmanChatRequest) -> dict[str, Any]:
    return handle_draftsman_chat(request)


@app.post("/api/draftsman/chat/", include_in_schema=False)
def draftsman_chat_trailing_slash(request: DraftsmanChatRequest) -> dict[str, Any]:
    return handle_draftsman_chat(request)


@app.post("/api/draftman/chat", include_in_schema=False)
def draftman_chat_typo_alias(request: DraftsmanChatRequest) -> dict[str, Any]:
    return handle_draftsman_chat(request)


@app.post("/api/draftman/chat/", include_in_schema=False)
def draftman_chat_typo_alias_trailing_slash(request: DraftsmanChatRequest) -> dict[str, Any]:
    return handle_draftsman_chat(request)


def handle_draftsman_chat(request: DraftsmanChatRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    config_path = workspace_config_path(root)
    config = read_yaml(config_path) if config_path.exists() else {}
    status = draftsman_config_status(config)
    if not status["ok"]:
        raise HTTPException(status_code=400, detail=status)
    if status["mode"] == "disabled":
        raise HTTPException(status_code=400, detail={"message": "Draftsman is disabled for this workspace.", "status": status})
    if status["mode"] == "external":
        raise HTTPException(
            status_code=400,
            detail={
                "message": "Workspace is configured for an external Draftsman. Switch to Embedded ChatGPT Sign-In in Configuration to chat inside the app.",
                "status": status,
            },
        )
    if not status["embeddedDraftsmanAvailable"]:
        raise HTTPException(
            status_code=401,
            detail={
                "message": "Sign in with ChatGPT before using the embedded Draftsman.",
                "status": status,
            },
        )
    return call_embedded_draftsman(root, config, request)


@app.get("/api/draftsman/oauth/openai/status")
def draftsman_openai_oauth_status(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    config_path = workspace_config_path(root)
    config = read_yaml(config_path) if config_path.exists() else {}
    status = draftsman_config_status(config)
    return {
        "ok": status["ok"],
        "workspace": str(root),
        "provider": "openai-codex",
        "auth": "chatgpt-codex-oauth",
        "signedIn": status["auth"]["signedIn"],
        "runtimeConfigured": status["auth"]["signedIn"],
        "runtimeAvailable": status["auth"]["signedIn"],
        "implementationStatus": status["embeddedImplementationStatus"],
        "apiKeysAllowed": False,
        "clientId": status.get("oauthClientId", OPENAI_CODEX_CLIENT_ID),
        "redirectUri": status.get("oauthRedirectUri", ""),
        "tokenStore": status["auth"]["tokenStore"],
        "accountId": status["auth"]["accountId"],
        "email": status["auth"]["email"],
        "planType": status["auth"]["planType"],
        "expiresAt": status["auth"]["expiresAt"],
        "note": status["note"],
    }


@app.get("/api/draftsman/oauth/openai/start")
def draftsman_openai_oauth_start(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    resolve_workspace(workspace)
    ensure_openai_codex_callback_server()
    verifier = pkce_verifier()
    state = secrets.token_urlsafe(32)
    expires_at = now_epoch() + 600
    with OAUTH_LOCK:
        OAUTH_PENDING[state] = {
            "verifier": verifier,
            "workspace": workspace or "",
            "expiresAtEpoch": expires_at,
        }
    params = {
        "client_id": OPENAI_CODEX_CLIENT_ID,
        "response_type": "code",
        "redirect_uri": OPENAI_CODEX_REDIRECT_URI,
        "scope": OPENAI_CODEX_SCOPE,
        "code_challenge": pkce_challenge(verifier),
        "code_challenge_method": "S256",
        "state": state,
        "id_token_add_organizations": "true",
        "codex_cli_simplified_flow": "true",
    }
    auth_url = f"{OPENAI_CODEX_AUTH_URL}?{urllib.parse.urlencode(params)}"
    return {
        "ok": True,
        "authUrl": auth_url,
        "state": state,
        "expiresAt": iso_from_epoch(expires_at),
        "callbackListener": f"http://{OPENAI_CODEX_CALLBACK_HOST}:{OPENAI_CODEX_CALLBACK_PORT}/auth/callback",
        "tokenStore": str(AUTH_STORE_PATH),
        "apiKeysAllowed": False,
    }


@app.post("/api/draftsman/oauth/openai/complete")
def draftsman_openai_oauth_complete(request: DraftsmanAuthCodeRequest) -> dict[str, Any]:
    resolve_workspace(request.workspace)
    result = complete_openai_codex_oauth(request.state, request.code)
    if not result.get("ok"):
        raise HTTPException(status_code=400, detail=result)
    return result


@app.post("/api/draftsman/oauth/openai/import-codex")
def draftsman_openai_oauth_import_codex(request: WorkspaceRequest) -> dict[str, Any]:
    resolve_workspace(request.workspace)
    profile = import_codex_cli_auth()
    return {
        "ok": True,
        "profile": auth_profile_public(profile),
        "tokenStore": str(AUTH_STORE_PATH),
    }


@app.post("/api/draftsman/oauth/openai/logout")
def draftsman_openai_oauth_logout(request: WorkspaceRequest) -> dict[str, Any]:
    resolve_workspace(request.workspace)
    return {
        "ok": True,
        "removed": delete_auth_profile(),
        "tokenStore": str(AUTH_STORE_PATH),
    }


@app.get("/api/draftsman/oauth/openai/callback")
def draftsman_openai_oauth_callback() -> dict[str, Any]:
    return {
        "ok": False,
        "message": "ChatGPT/Codex OAuth callbacks are handled by the local listener at http://127.0.0.1:1455/auth/callback.",
        "start": "/api/draftsman/oauth/openai/start",
        "apiKeysAllowed": False,
    }


@app.get("/api/framework/updates")
def framework_updates(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    lock_path = root / ".draft" / "framework.lock"
    lock = read_yaml(lock_path) if lock_path.exists() else {}
    current = framework_pin()
    pinned = ((lock.get("framework") or {}).get("pinnedCommit") if isinstance(lock.get("framework"), dict) else "")
    return {
        "workspace": str(root),
        "lockPath": str(lock_path),
        "locked": lock,
        "currentFramework": current,
        "updateAvailable": bool(pinned and current.get("pinnedCommit") and pinned != current.get("pinnedCommit")),
        "note": "This compares the workspace lock to the running framework checkout. Remote update checks should use the configured GitHub integration.",
    }


@app.get("/api/workspace/config")
def workspace_config(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    config_path = workspace_config_path(root)
    if not config_path.exists():
        return {"workspace": str(root), "configured": False}
    return {"workspace": str(root), "configured": True, "config": read_yaml(config_path)}


@app.post("/api/workspace/init")
def workspace_init(request: WorkspaceInitRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace, must_exist=False)
    return initialize_workspace_files(root, request)


@app.put("/api/workspace/config")
def update_workspace_config(request: WorkspaceSettingsRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    config_path = workspace_config_path(root)
    write_yaml(config_path, request.config)
    return {"ok": True, "workspace": str(root), "path": str(config_path)}


@app.get("/api/workspace/effective-model")
def get_effective_model(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    return effective_model(resolve_workspace(workspace))


@app.get("/api/catalog/objects")
def catalog_objects(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    model = effective_model(resolve_workspace(workspace))
    return {"objects": [obj for obj in model["objects"] if obj.get("layer") == "catalog"]}


@app.get("/api/catalog/browser")
def catalog_browser(workspace: Optional[str] = Query(default=None)) -> FileResponse:
    root = resolve_workspace(workspace)
    digest = hashlib.sha256(str(root).encode("utf-8")).hexdigest()[:16]
    output_path = Path(tempfile.gettempdir()) / f"draft-catalog-browser-{digest}.html"
    completed = run(
        [
            sys.executable,
            str(FRAMEWORK_ROOT / "tools" / "generate_browser.py"),
            "--workspace",
            str(root),
            "--output",
            str(output_path),
        ],
        REPO_ROOT,
    )
    if completed.returncode != 0:
        raise HTTPException(status_code=500, detail=completed.stderr or completed.stdout)
    return FileResponse(output_path, media_type="text/html")


@app.post("/api/workspace/validate")
def validate_workspace(request: WorkspaceRequest) -> dict[str, Any]:
    return validate_workspace_result(resolve_workspace(request.workspace))


@app.post("/api/objects/upsert")
def upsert_object(request: ObjectWriteRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    ensure_working_branch(root)
    document = dict(request.document)
    output_path = object_output_path(root, document, request.layer, request.path)
    write_yaml(output_path, document)
    result: dict[str, Any] = {
        "ok": True,
        "workspace": str(root),
        "path": output_path.relative_to(root).as_posix(),
        "id": document.get("id"),
        "type": document.get("type"),
    }
    if request.validateAfter:
        result["validation"] = validate_workspace_result(root)
    return result


@app.post("/api/object-patches/upsert")
def upsert_object_patch(request: ObjectPatchWriteRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    ensure_working_branch(root)
    patch_id = f"patch.{slug(request.target)}.{slug(request.purpose)}"
    document: dict[str, Any] = {
        "schemaVersion": "1.0",
        "id": patch_id,
        "type": "object_patch",
        "name": request.name or f"{request.target} {request.purpose}",
        "description": request.description or "App-generated object patch.",
        "catalogStatus": request.catalogStatus,
        "lifecycleStatus": request.lifecycleStatus,
        "target": request.target,
        "patch": request.patch,
    }
    if request.owner:
        document["owner"] = request.owner
    if request.tags:
        document["tags"] = request.tags
    output_path = object_output_path(root, document, "configurations", None)
    write_yaml(output_path, document)
    result: dict[str, Any] = {
        "ok": True,
        "workspace": str(root),
        "path": output_path.relative_to(root).as_posix(),
        "id": patch_id,
        "target": request.target,
    }
    if request.validateAfter:
        result["validation"] = validate_workspace_result(root)
    return result


@app.get("/api/git/status")
def git_status(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    root = resolve_workspace(workspace)
    completed = run(["git", "status", "--short", "--branch"], root)
    return {"ok": completed.returncode == 0, "stdout": completed.stdout, "stderr": completed.stderr}


@app.post("/api/git/commit")
def git_commit(request: CommitRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    ensure_working_branch(root)
    paths = request.paths or ["catalog", "configurations", ".draft"]
    add = run(["git", "add", *paths], root)
    if add.returncode != 0:
        return {"ok": False, "stage": "add", "stdout": add.stdout, "stderr": add.stderr}
    commit = run(["git", "commit", "-m", request.message], root)
    return {"ok": commit.returncode == 0, "stdout": commit.stdout, "stderr": commit.stderr}


@app.post("/api/git/push")
def git_push(request: PushRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    branch = request.branch
    if not branch:
        current = run(["git", "branch", "--show-current"], root)
        branch = current.stdout.strip() if current.returncode == 0 else "dev"
    completed = run(["git", "push", request.remote, branch], root)
    return {"ok": completed.returncode == 0, "stdout": completed.stdout, "stderr": completed.stderr}


@app.post("/api/publish")
def publish(request: PublishRequest) -> dict[str, Any]:
    root = resolve_workspace(request.workspace)
    repo = workspace_repository_config(root)
    base = request.base or str(repo["defaultBranch"])
    head = request.head or str(repo["devBranch"])
    mode = request.mode or str(repo["publishMode"])
    if mode == "direct":
        completed = run(["git", "push", "origin", f"{head}:{base}"], root)
        return {"ok": completed.returncode == 0, "mode": "direct", "stdout": completed.stdout, "stderr": completed.stderr}
    completed = run(
        [
            "gh",
            "pr",
            "create",
            "--base",
            base,
            "--head",
            head,
            "--title",
            request.title,
            "--body",
            request.body,
        ],
        root,
    )
    return {"ok": completed.returncode == 0, "mode": "pull-request", "stdout": completed.stdout, "stderr": completed.stderr}


@app.get("/api/automation/readiness")
def automation_readiness(workspace: Optional[str] = Query(default=None)) -> dict[str, Any]:
    model = effective_model(resolve_workspace(workspace))
    candidates = [
        obj for obj in model["objects"]
        if obj.get("type") in {"rbb", "reference_architecture", "software_distribution_manifest"}
    ]
    return {
        "status": "informational",
        "message": "Automation readiness scoring is reserved for deployable architecture mappings.",
        "candidateCount": len(candidates),
        "candidates": candidates,
    }
